version: "2"

services:
  openvpn:
    build:
      context: .
    networks:
      - vpn
    volumes:
      - ~/vpn:/root/client-configs/files
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194"
    restart: always
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - CLIENT_NAME=${CLIENT_NAME}

networks:
  vpn:
